"""initial schema

Revision ID: 48e2bea4bcb5
Revises: 
Create Date: 2026-09-15 19:11:22.600170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e2bea4bcb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application')),
    sa.UniqueConstraint('name', name=op.f('uq_application_name'))
    )
    op.create_table('audit_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    op.create_index(op.f('ix_audit_event_action'), 'audit_event', ['action'], unique=False)
    op.create_index(op.f('ix_audit_event_correlation_id'), 'audit_event', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_event_object_id'), 'audit_event', ['object_id'], unique=False)
    op.create_index(op.f('ix_audit_event_timestamp'), 'audit_event', ['timestamp'], unique=False)
    op.create_table('identity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_employee_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('worker_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('manager_identity_id', sa.String(length=36), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=30), nullable=False),
    sa.Column('source_status_date_conflict', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manager_identity_id'], ['identity.id'], name=op.f('fk_identity_manager_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity'))
    )
    op.create_index(op.f('ix_identity_canonical_employee_id'), 'identity', ['canonical_employee_id'], unique=False)
    op.create_index(op.f('ix_identity_email'), 'identity', ['email'], unique=False)
    op.create_index(op.f('ix_identity_lifecycle_status'), 'identity', ['lifecycle_status'], unique=False)
    op.create_table('ingestion_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('input_path', sa.String(length=500), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_in', sa.Integer(), nullable=False),
    sa.Column('rows_normalized', sa.Integer(), nullable=False),
    sa.Column('rows_quarantined', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_run'))
    )
    op.create_index(op.f('ix_ingestion_run_input_hash'), 'ingestion_run', ['input_hash'], unique=False)
    op.create_index('ix_ingestion_run_source_started', 'ingestion_run', ['source_system', 'started_at'], unique=False)
    op.create_index(op.f('ix_ingestion_run_source_system'), 'ingestion_run', ['source_system'], unique=False)
    op.create_table('campaign',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('ingestion_watermark', sa.String(length=36), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('launched_with_stale_source', sa.Boolean(), nullable=False),
    sa.Column('stale_source_override_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_watermark'], ['ingestion_run.id'], name=op.f('fk_campaign_ingestion_watermark_ingestion_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign'))
    )
    op.create_index(op.f('ix_campaign_status'), 'campaign', ['status'], unique=False)
    op.create_table('entitlement',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('native_id', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('privileged', sa.Boolean(), nullable=False),
    sa.Column('ent_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], name=op.f('fk_entitlement_application_id_application')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entitlement'))
    )
    op.create_index('ix_entitlement_app_native', 'entitlement', ['application_id', 'native_id'], unique=True)
    op.create_index(op.f('ix_entitlement_application_id'), 'entitlement', ['application_id'], unique=False)
    op.create_table('finding',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('formula_inputs', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_run.id'], name=op.f('fk_finding_run_id_ingestion_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding'))
    )
    op.create_index(op.f('ix_finding_rule_code'), 'finding', ['rule_code'], unique=False)
    op.create_index('ix_finding_rule_status', 'finding', ['rule_code', 'status'], unique=False)
    op.create_index(op.f('ix_finding_status'), 'finding', ['status'], unique=False)
    op.create_index(op.f('ix_finding_subject_id'), 'finding', ['subject_id'], unique=False)
    op.create_table('reconciliation_metric',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_run.id'], name=op.f('fk_reconciliation_metric_run_id_ingestion_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_metric'))
    )
    op.create_index(op.f('ix_reconciliation_metric_run_id'), 'reconciliation_metric', ['run_id'], unique=False)
    op.create_table('source_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=False),
    sa.Column('source_sheet', sa.String(length=200), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('raw_hash', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_run.id'], name=op.f('fk_source_record_run_id_ingestion_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_record')),
    sa.UniqueConstraint('source_system', 'source_file', 'source_sheet', 'source_line', 'raw_hash', name='uq_source_record_identity')
    )
    op.create_index('ix_source_record_file_line', 'source_record', ['source_file', 'source_line'], unique=False)
    op.create_index(op.f('ix_source_record_raw_hash'), 'source_record', ['raw_hash'], unique=False)
    op.create_index(op.f('ix_source_record_run_id'), 'source_record', ['run_id'], unique=False)
    op.create_index(op.f('ix_source_record_source_system'), 'source_record', ['source_system'], unique=False)
    op.create_table('workflow_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_type', sa.String(length=20), nullable=False),
    sa.Column('subject_identity_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_event_id', sa.String(length=200), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_identity_id'], ['identity.id'], name=op.f('fk_workflow_run_subject_identity_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_run'))
    )
    op.create_index(op.f('ix_workflow_run_idempotency_key'), 'workflow_run', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_workflow_run_status'), 'workflow_run', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_run_subject_identity_id'), 'workflow_run', ['subject_identity_id'], unique=False)
    op.create_index(op.f('ix_workflow_run_trigger_event_id'), 'workflow_run', ['trigger_event_id'], unique=False)
    op.create_index(op.f('ix_workflow_run_workflow_type'), 'workflow_run', ['workflow_type'], unique=False)
    op.create_table('access_request',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('entitlement_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('policy', sa.String(length=100), nullable=False),
    sa.Column('approver_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['identity.id'], name=op.f('fk_access_request_approver_id_identity')),
    sa.ForeignKeyConstraint(['entitlement_id'], ['entitlement.id'], name=op.f('fk_access_request_entitlement_id_entitlement')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_access_request_identity_id_identity')),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_run.id'], name=op.f('fk_access_request_workflow_run_id_workflow_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_request'))
    )
    op.create_index(op.f('ix_access_request_entitlement_id'), 'access_request', ['entitlement_id'], unique=False)
    op.create_index(op.f('ix_access_request_identity_id'), 'access_request', ['identity_id'], unique=False)
    op.create_table('account',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('native_id', sa.String(length=300), nullable=False),
    sa.Column('username', sa.String(length=300), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('owner_identity_id', sa.String(length=36), nullable=True),
    sa.Column('ownership_status', sa.String(length=30), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], name=op.f('fk_account_application_id_application')),
    sa.ForeignKeyConstraint(['owner_identity_id'], ['identity.id'], name=op.f('fk_account_owner_identity_id_identity')),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], name=op.f('fk_account_source_record_id_source_record')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account'))
    )
    op.create_index('ix_account_app_native', 'account', ['application_id', 'native_id'], unique=True)
    op.create_index(op.f('ix_account_application_id'), 'account', ['application_id'], unique=False)
    op.create_index(op.f('ix_account_owner_identity_id'), 'account', ['owner_identity_id'], unique=False)
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=False)
    op.create_table('entitlement_edge',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_entitlement_id', sa.String(length=36), nullable=False),
    sa.Column('child_entitlement_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_entitlement_id'], ['entitlement.id'], name=op.f('fk_entitlement_edge_child_entitlement_id_entitlement')),
    sa.ForeignKeyConstraint(['parent_entitlement_id'], ['entitlement.id'], name=op.f('fk_entitlement_edge_parent_entitlement_id_entitlement')),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], name=op.f('fk_entitlement_edge_source_record_id_source_record')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entitlement_edge'))
    )
    op.create_index(op.f('ix_entitlement_edge_child_entitlement_id'), 'entitlement_edge', ['child_entitlement_id'], unique=False)
    op.create_index(op.f('ix_entitlement_edge_parent_entitlement_id'), 'entitlement_edge', ['parent_entitlement_id'], unique=False)
    op.create_index('ix_entitlement_edge_unique', 'entitlement_edge', ['parent_entitlement_id', 'child_entitlement_id'], unique=True)
    op.create_table('finding_disposition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('finding_key', sa.String(length=300), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], name=op.f('fk_finding_disposition_finding_id_finding')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding_disposition'))
    )
    op.create_index(op.f('ix_finding_disposition_finding_id'), 'finding_disposition', ['finding_id'], unique=False)
    op.create_index(op.f('ix_finding_disposition_finding_key'), 'finding_disposition', ['finding_key'], unique=False)
    op.create_table('identity_alias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('alias_type', sa.String(length=30), nullable=False),
    sa.Column('normalized_value', sa.String(length=300), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_identity_alias_identity_id_identity')),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], name=op.f('fk_identity_alias_source_record_id_source_record')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_alias'))
    )
    op.create_index(op.f('ix_identity_alias_identity_id'), 'identity_alias', ['identity_id'], unique=False)
    op.create_index(op.f('ix_identity_alias_normalized_value'), 'identity_alias', ['normalized_value'], unique=False)
    op.create_table('quarantine_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('candidate_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], name=op.f('fk_quarantine_record_source_record_id_source_record')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quarantine_record'))
    )
    op.create_index(op.f('ix_quarantine_record_reason_code'), 'quarantine_record', ['reason_code'], unique=False)
    op.create_index(op.f('ix_quarantine_record_source_record_id'), 'quarantine_record', ['source_record_id'], unique=False)
    op.create_table('workflow_step',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('compensation_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_run.id'], name=op.f('fk_workflow_step_run_id_workflow_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_step'))
    )
    op.create_index(op.f('ix_workflow_step_run_id'), 'workflow_step', ['run_id'], unique=False)
    op.create_table('account_entitlement',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('entitlement_id', sa.String(length=36), nullable=False),
    sa.Column('grant_type', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_account_entitlement_account_id_account')),
    sa.ForeignKeyConstraint(['entitlement_id'], ['entitlement.id'], name=op.f('fk_account_entitlement_entitlement_id_entitlement')),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], name=op.f('fk_account_entitlement_source_record_id_source_record')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_entitlement'))
    )
    op.create_index(op.f('ix_account_entitlement_account_id'), 'account_entitlement', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_entitlement_entitlement_id'), 'account_entitlement', ['entitlement_id'], unique=False)
    op.create_index('ix_account_entitlement_unique', 'account_entitlement', ['account_id', 'entitlement_id'], unique=True)
    op.create_table('account_relationship',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_account_id', sa.String(length=36), nullable=False),
    sa.Column('target_account_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('source_record_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_account_id'], ['account.id'], name=op.f('fk_account_relationship_source_account_id_account')),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_record.id'], name=op.f('fk_account_relationship_source_record_id_source_record')),
    sa.ForeignKeyConstraint(['target_account_id'], ['account.id'], name=op.f('fk_account_relationship_target_account_id_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_relationship'))
    )
    op.create_index(op.f('ix_account_relationship_source_account_id'), 'account_relationship', ['source_account_id'], unique=False)
    op.create_index(op.f('ix_account_relationship_target_account_id'), 'account_relationship', ['target_account_id'], unique=False)
    op.create_table('correlation_decision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_correlation_decision_account_id_account')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_correlation_decision_identity_id_identity')),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_run.id'], name=op.f('fk_correlation_decision_run_id_ingestion_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correlation_decision'))
    )
    op.create_index(op.f('ix_correlation_decision_account_id'), 'correlation_decision', ['account_id'], unique=False)
    op.create_index(op.f('ix_correlation_decision_identity_id'), 'correlation_decision', ['identity_id'], unique=False)
    op.create_table('review_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('entitlement_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_route', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_review_item_account_id_account')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('fk_review_item_campaign_id_campaign')),
    sa.ForeignKeyConstraint(['entitlement_id'], ['entitlement.id'], name=op.f('fk_review_item_entitlement_id_entitlement')),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], name=op.f('fk_review_item_identity_id_identity')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['identity.id'], name=op.f('fk_review_item_reviewer_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_item'))
    )
    op.create_index(op.f('ix_review_item_account_id'), 'review_item', ['account_id'], unique=False)
    op.create_index(op.f('ix_review_item_campaign_id'), 'review_item', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_review_item_entitlement_id'), 'review_item', ['entitlement_id'], unique=False)
    op.create_index(op.f('ix_review_item_identity_id'), 'review_item', ['identity_id'], unique=False)
    op.create_index(op.f('ix_review_item_reviewer_id'), 'review_item', ['reviewer_id'], unique=False)
    op.create_table('reminder',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_item_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_item.id'], name=op.f('fk_reminder_review_item_id_review_item')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['identity.id'], name=op.f('fk_reminder_reviewer_id_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminder'))
    )
    op.create_index(op.f('ix_reminder_review_item_id'), 'reminder', ['review_item_id'], unique=False)
    op.create_table('revocation_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_item_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=36), nullable=True),
    sa.Column('execution_status', sa.String(length=20), nullable=False),
    sa.Column('proof', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_item.id'], name=op.f('fk_revocation_task_review_item_id_review_item')),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_run.id'], name=op.f('fk_revocation_task_workflow_run_id_workflow_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revocation_task'))
    )
    op.create_index(op.f('ix_revocation_task_review_item_id'), 'revocation_task', ['review_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revocation_task_review_item_id'), table_name='revocation_task')
    op.drop_table('revocation_task')
    op.drop_index(op.f('ix_reminder_review_item_id'), table_name='reminder')
    op.drop_table('reminder')
    op.drop_index(op.f('ix_review_item_reviewer_id'), table_name='review_item')
    op.drop_index(op.f('ix_review_item_identity_id'), table_name='review_item')
    op.drop_index(op.f('ix_review_item_entitlement_id'), table_name='review_item')
    op.drop_index(op.f('ix_review_item_campaign_id'), table_name='review_item')
    op.drop_index(op.f('ix_review_item_account_id'), table_name='review_item')
    op.drop_table('review_item')
    op.drop_index(op.f('ix_correlation_decision_identity_id'), table_name='correlation_decision')
    op.drop_index(op.f('ix_correlation_decision_account_id'), table_name='correlation_decision')
    op.drop_table('correlation_decision')
    op.drop_index(op.f('ix_account_relationship_target_account_id'), table_name='account_relationship')
    op.drop_index(op.f('ix_account_relationship_source_account_id'), table_name='account_relationship')
    op.drop_table('account_relationship')
    op.drop_index('ix_account_entitlement_unique', table_name='account_entitlement')
    op.drop_index(op.f('ix_account_entitlement_entitlement_id'), table_name='account_entitlement')
    op.drop_index(op.f('ix_account_entitlement_account_id'), table_name='account_entitlement')
    op.drop_table('account_entitlement')
    op.drop_index(op.f('ix_workflow_step_run_id'), table_name='workflow_step')
    op.drop_table('workflow_step')
    op.drop_index(op.f('ix_quarantine_record_source_record_id'), table_name='quarantine_record')
    op.drop_index(op.f('ix_quarantine_record_reason_code'), table_name='quarantine_record')
    op.drop_table('quarantine_record')
    op.drop_index(op.f('ix_identity_alias_normalized_value'), table_name='identity_alias')
    op.drop_index(op.f('ix_identity_alias_identity_id'), table_name='identity_alias')
    op.drop_table('identity_alias')
    op.drop_index(op.f('ix_finding_disposition_finding_key'), table_name='finding_disposition')
    op.drop_index(op.f('ix_finding_disposition_finding_id'), table_name='finding_disposition')
    op.drop_table('finding_disposition')
    op.drop_index('ix_entitlement_edge_unique', table_name='entitlement_edge')
    op.drop_index(op.f('ix_entitlement_edge_parent_entitlement_id'), table_name='entitlement_edge')
    op.drop_index(op.f('ix_entitlement_edge_child_entitlement_id'), table_name='entitlement_edge')
    op.drop_table('entitlement_edge')
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_index(op.f('ix_account_owner_identity_id'), table_name='account')
    op.drop_index(op.f('ix_account_application_id'), table_name='account')
    op.drop_index('ix_account_app_native', table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_access_request_identity_id'), table_name='access_request')
    op.drop_index(op.f('ix_access_request_entitlement_id'), table_name='access_request')
    op.drop_table('access_request')
    op.drop_index(op.f('ix_workflow_run_workflow_type'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_trigger_event_id'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_subject_identity_id'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_status'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_idempotency_key'), table_name='workflow_run')
    op.drop_table('workflow_run')
    op.drop_index(op.f('ix_source_record_source_system'), table_name='source_record')
    op.drop_index(op.f('ix_source_record_run_id'), table_name='source_record')
    op.drop_index(op.f('ix_source_record_raw_hash'), table_name='source_record')
    op.drop_index('ix_source_record_file_line', table_name='source_record')
    op.drop_table('source_record')
    op.drop_index(op.f('ix_reconciliation_metric_run_id'), table_name='reconciliation_metric')
    op.drop_table('reconciliation_metric')
    op.drop_index(op.f('ix_finding_subject_id'), table_name='finding')
    op.drop_index(op.f('ix_finding_status'), table_name='finding')
    op.drop_index('ix_finding_rule_status', table_name='finding')
    op.drop_index(op.f('ix_finding_rule_code'), table_name='finding')
    op.drop_table('finding')
    op.drop_index(op.f('ix_entitlement_application_id'), table_name='entitlement')
    op.drop_index('ix_entitlement_app_native', table_name='entitlement')
    op.drop_table('entitlement')
    op.drop_index(op.f('ix_campaign_status'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_ingestion_run_source_system'), table_name='ingestion_run')
    op.drop_index('ix_ingestion_run_source_started', table_name='ingestion_run')
    op.drop_index(op.f('ix_ingestion_run_input_hash'), table_name='ingestion_run')
    op.drop_table('ingestion_run')
    op.drop_index(op.f('ix_identity_lifecycle_status'), table_name='identity')
    op.drop_index(op.f('ix_identity_email'), table_name='identity')
    op.drop_index(op.f('ix_identity_canonical_employee_id'), table_name='identity')
    op.drop_table('identity')
    op.drop_index(op.f('ix_audit_event_timestamp'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_object_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_correlation_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_action'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_table('application')
    # ### end Alembic commands ###
